# ==================== FromConfig Launcher Config ======================
# These parameters are used by FromConfig to instantiate a launcher.
# The launcher is responsible for parsing, logging, instantiating and
# executing the config and Fire command.
# ======================================================================
# Configure hyper parameters, use interpolation ${hparams.key} to use them
hparams:
  learning_rate: [0.1, 0.001]
  dim: [10, 100]

# Configure logging level (set to logging.INFO)
logging:
  level: 20

# Configure parser (optional, using this parser is the default behavior)
parser:
  _attr_: "fromconfig.parser.DefaultParser"

# Configure launcher (optional, the following config creates the same launcher as the default behavior)
launcher:
  sweep: hparams
  log: logging
  parse: parser
  run: local
